# -*- coding: utf-8 -*-
path = 'backend/src/main/java/com/exam408/config/DataInitializer.java'

with open(path, 'rb') as f:
    text = f.read().decode('utf-8')

marker = "    private boolean loadQuestionsFromJson()"
idx = text.find(marker)
assert idx >= 0, "找不到 loadQuestionsFromJson"

# 我现在用更可靠的方式来写 Java 代码 —— 用一个辅助函数处理特定的转义
# 实际上，最简单方式：用 mapper.writeValueAsString 把 list 直接转成 json string
# 但这里 options 是 ["A.xxx", ...]，需要转换成 [{key, text}, ...]

L = []
def a(s):
    L.append(s)

a('    private boolean loadQuestionsFromJson() {')
a('        try {')
a('            String dataDir = "c:/projects/408真题训练系统/src/main/resources/static/choice";')
a('            File dir = new File(dataDir);')
a('            if (!dir.exists() || !dir.isDirectory()) {')
a('                log.warn("数据目录不存在: {}", dataDir);')
a('                return false;')
a('            }')
a('')
a('            ObjectMapper mapper = new ObjectMapper();')
a('            int total = 0;')
a('')
a('            // 遍历 2009-2025 所有年份')
a('            for (int year = 2009; year <= 2025; year++) {')
a('                File jsonFile = new File(dataDir, year + ".json");')
a('                if (!jsonFile.exists()) {')
a('                    log.warn("{} 不存在，跳过", jsonFile.getName());')
a('                    continue;')
a('                }')
a('')
a('                List<Map<String, Object>> data = mapper.readValue(jsonFile,')
a('                    new TypeReference<List<Map<String, Object>>>() {});')
a('')
a('                for (Map<String, Object> item : data) {')
a('                    Question q = new Question();')
a('')
a('                    // 年份')
a('                    q.setExamYear(year);')
a('')
a('                    // 题号')
a('                    Integer qNum = (Integer) item.get("题号");')
a('                    if (qNum == null) {')
a('                        qNum = (Integer) item.get("question_number");')
a('                    }')
a('                    if (qNum != null) q.setQuestionNumber(qNum);')
a('')
a('                    // 科目：优先从 JSON 读取')
a('                    String subjectField = (String) item.get("科目");')
a('                    if (subjectField != null && !subjectField.isEmpty()) {')
a('                        q.setSubject(subjectField);')
a('                    } else {')
a('                        q.setSubject(determineSubject(qNum != null ? qNum : 1));')
a('                    }')
a('')
a('                    // 类型 (所有数据都是单选题，1-40题)')
a('                    q.setType("单选");')
a('')
a('                    // 内容')
a('                    String content = (String) item.get("内容");')
a('                    q.setContent(content != null ? content : "");')
a('')
a('                    // 选项: 把 ["A.xxx", "B.xxx", ...] 转换为 [{key, text}, ...] 的 JSON 字符串')
a('                    Object optionsObj = item.get("选项");')
a('                    if (optionsObj instanceof List) {')
a('                        List<String> optionsList = (List<String>) optionsObj;')
a('                        List<Map<String, String>> optMapList = new java.util.ArrayList<>();')
a('                        for (int i = 0; i < optionsList.size(); i++) {')
a('                            String opt = optionsList.get(i);')
a('                            char key = opt.charAt(0);')
a('                            String text2 = opt.length() > 2 ? opt.substring(2).trim() : "";')
a('                            Map<String, String> m = new java.util.HashMap<>();')
a('                            m.put("key", String.valueOf(key));')
a('                            m.put("text", text2);')
a('                            optMapList.add(m);')
a('                        }')
a('                        q.setOptions(mapper.writeValueAsString(optMapList));')
a('                    }')
a('')
a('                    // 答案')
a('                    String answer = (String) item.get("答案");')
a('                    if (answer != null && !answer.isEmpty()) {')
a('                        q.setAnswer(answer.trim());')
a('                    } else {')
a('                        q.setAnswer("");')
a('                    }')
a('')
a('                    // 解析')
a('                    String analysis = (String) item.get("解析");')
a('                    q.setAnalysis(analysis != null ? analysis : "");')
a('')
a('                    // 知识点标签：优先从 JSON 读取')
a('                    Object tagsObj = item.get("标签");')
a('                    String knowledgeTagValue;')
a('                    if (tagsObj instanceof List) {')
a('                        List<String> tList = (List<String>) tagsObj;')
a('                        StringBuilder sb = new StringBuilder();')
a('                        for (int i = 0; i < tList.size(); i++) {')
a('                            if (i > 0) sb.append(",");')
a('                            sb.append(tList.get(i));')
a('                        }')
a('                        knowledgeTagValue = sb.toString();')
a('                    } else if (tagsObj instanceof String) {')
a('                        knowledgeTagValue = (String) tagsObj;')
a('                    } else {')
a('                        knowledgeTagValue = "";')
a('                    }')
a('')
a('                    // 章节')
a('                    Object chapterObj = item.get("章节");')
a('                    String chapterValue = "";')
a('                    if (chapterObj instanceof List) {')
a('                        List<String> chList = (List<String>) chapterObj;')
a('                        StringBuilder sb = new StringBuilder();')
a('                        for (int i = 0; i < chList.size(); i++) {')
a('                            if (i > 0) sb.append(",");')
a('                            sb.append(chList.get(i));')
a('                        }')
a('                        chapterValue = sb.toString();')
a('                    } else if (chapterObj instanceof String) {')
a('                        chapterValue = (String) chapterObj;')
a('                    }')
a('')
a('                    // 设置 knowledgeTag：科目 — 章节 — 标签')
a('                    String composite = q.getSubject()')
a('                        + (chapterValue.isEmpty() ? "" : " — " + chapterValue)')
a('                        + (knowledgeTagValue.isEmpty() ? "" : " — " + knowledgeTagValue);')
a('                    q.setKnowledgeTag(composite);')
a('                    q.setKnowledgeTags(knowledgeTagValue);')
a('')
a('                    questionMapper.insert(q);')
a('                    total++;')
a('                }')
a('                log.info("已加载 {} ({}道)", jsonFile.getName(), data.size());')
a('            }')
a('')
a('            log.info("共从 JSON 文件加载 {} 道题目", total);')
a('            return total > 0;')
a('        } catch (Exception e) {')
a('            log.error("从 JSON 文件加载数据失败: {}", e.getMessage(), e);')
a('            return false;')
a('        }')
a('    }')
a('')
a('    private String determineSubject(int qNum) {')
a('        if (qNum <= 11 || qNum == 41 || qNum == 42) return "数据结构";')
a('        if (qNum <= 22 || qNum == 43 || qNum == 44) return "计算机组成原理";')
a('        if (qNum <= 32 || qNum == 45 || qNum == 46) return "操作系统";')
a('        return "计算机网络";')
a('    }')
a('}')
a('')

new_code = '\n'.join(L)
final_text = text[:idx] + new_code

with open(path, 'wb') as f:
    f.write(final_text.encode('utf-8'))

print("已修复，新文件长度: ", len(final_text))
